<a href="https://colab.research.google.com/github/Asilbek-dev309/Asilbek-dev309/blob/main/Deep_learning_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from fastai.tabular.all import *
from fastai.tabular.all import *
path=untar_data(URLs.ADULT_SAMPLE)
dls=TabularDataLoaders.from_csv(path/'adult.csv',path=path,bs=64,y_names='salary',
                                cat_names=['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex'],
                                cont_names=['age','fnlwgt','education-num','capital-gain','capital-loss','hours-per-week'],
                                procs=[Categorify,FillMissing,Normalize])


learn=tabular_learner(dls,metrics=accuracy)

learn.fit_one_cycle(4)


learn=tabular_learner(dls,metrics=accuracy)

learn.fit_one_cycle(4)

SyntaxError: positional argument follows keyword argument (<ipython-input-1-072fb1f675fd>, line 4)

In [ ]:
from fastai.tabular.all import *
from fastai.tabular.all import *
path=untar_data(URLs.ADULT_SAMPLE)
dls=TabularDataLoaders.from_csv(path/'adult.csv',path=path,bs=64,y_names='salary',skipinitialspace=False,
                                cat_names=['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race','sex'],
                                cont_names=['age','fnlwgt','education-num','capital-gain','capital-loss','hours-per-week'],
                                procs=[Categorify,FillMissing,Normalize])


learn=tabular_learner(dls,metrics=accuracy)

learn.fit_one_cycle(4)

/usr/local/lib/python3.11/dist-packages/fastai/tabular/core.py:314: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  to[n].fillna(self.na_dict[n], inplace=True)

In [ ]:
import pandas as pd
df=pd.read_csv(path/'adult.csv')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,49,Private,101320,Assoc-acdm,12.0,Married-civ-spouse,NaN,Wife,White,Female,0,1902,40,United-States,>=50k
1,44,Private,236746,Masters,14.0,Divorced,Exec-managerial,Not-in-family,White,Male,10520,0,45,United-States,>=50k
2,38,Private,96185,HS-grad,NaN,Divorced,NaN,Unmarried,Black,Female,0,0,32,United-States,<50k
3,38,Self-emp-inc,112847,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,United-States,>=50k
4,42,Self-emp-not-inc,82297,7th-8th,NaN,Married-civ-spouse,Other-service,Wife,Black,Female,0,0,50,United-States,<50k

In [ ]:
row,pred,probs=learn.predict(df.iloc[0])
pred.item(),probs

/usr/local/lib/python3.11/dist-packages/fastai/tabular/core.py:314: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  to[n].fillna(self.na_dict[n], inplace=True)

(1, tensor([0.0946, 0.9054]))